[build]
  publish = "out"
  command = "npm run build-prod"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  included_files = ["src/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"